require("ToolLibrary/UI/ModuleRenderable.lua")
require("ToolLibrary/UI/ModuleSkeleton.lua")
require("ToolLibrary/UI/ModuleCamera.lua")
require("ToolLibrary/UI/ModuleText.lua")
require("ToolLibrary/UI/ModuleScene.lua")
require("ToolLibrary/UI/ModuleLight.lua")
require("ToolLibrary/UI/ModuleSelectable.lua")
require("ToolLibrary/UI/ModuleRollover.lua")
require("ToolLibrary/UI/ModuleDialog.lua")
require("ToolLibrary/UI/ModuleDialogChoice.lua")
require("ToolLibrary/UI/ModuleTrigger.lua")
require("ToolLibrary/UI/ModuleWalkAnimator.lua")
require("ToolLibrary/UI/ModuleNavCam.lua")
require("ToolLibrary/UI/ModulePathingTo.lua")

function ModuleCollector_RegisterUI(Ver)

	ModuleRenderable_RegisterUI(Ver)
	ModuleSkeleton_RegisterUI(Ver)
	ModuleCamera_RegisterUI(Ver)
	ModuleText_RegisterUI(Ver)
    ModuleScene_RegisterUI(Ver)
	ModuleLight_RegisterUI(Ver)
	ModuleSelectable_RegisterUI(Ver)
	ModuleRollover_RegisterUI(Ver)
	ModuleDialog_RegisterUI(Ver)
	ModuleDialogChoice_RegisterUI(Ver)
	ModuleTrigger_RegisterUI(Ver)
	ModuleWalkAnimator_RegisterUI(Ver)
	ModuleNavCam_RegisterUI(Ver)
	ModulePathingTo_RegisterUI(Ver)

end